### ISSUE TITLE
Request: Build critical path

### ISSUE THREAD

**Issue by Maragues** [runningcode/gradle-doctor#143]
Given a a Baseline critical path, it'd be great if gradle-doctor threw a warning/error if a developer's PR changed the critical path for worse.

This would be specially useful in large teams, where it's really hard to control what devs add in order to get their tasks done, often disregarding metrics like build performance.

Reasoning:
When working in android multi-module projects, I wonder how important dependencies amongst modules are. Which modules are blockers to others, where's it's worth to invest time to try to remove the dependency on an expensive-to-build module.

Scan's Timeline view tells you the order in which tasks where run, and you can more or less see the build order, but it would be great it gradle-doctor could print the build critical path.

If this is not the right tool to request this feature, could you point out some documentation to read on the topic?

Thanks

**Comment by runningcode** [comment]
Hi Maragues, thanks for the feature request. Let me see if I fully understand this request.

Are you asking for a tool to keep track of whether a change made anywhere in the codebase would increase or decrease build times for a "critical path" i.e. `assembleDebug`?
In order to validate this, one would need to make the exact same change to the codebase and then run a benchmark against it. Changing a single file in a module in a base module will definitely slow down the next build that runs but likely won't have an impact on the overall build time of the critical path once this change is cached.
In order to validate whether or not the build time was affected by a change to the codebase, one would need to run the exact same changes to the codebase and then perform a benchmark against it. I recommend using the Gradle Profiler for this. https://github.com/gradle/gradle-profiler

I hope that answers your question. Let me know if that was unclear.

**Comment by Maragues** [comment]
Thanks @runningcode, my question comes more from a frustration of lack of knowing where to invest time when trying to reduce build times

Since we have very little influence on reducing task times on android (`kapt` is what it is), I had hopes that applying close architecture principles to our module dependencies would allow for more parallelization, thus faster fresh build times
![module dependency](https://user-images.githubusercontent.com/655970/103524491-f5ffe980-4e7d-11eb-83a7-e879181633be.png)

But, after applying the changes shown in the diagram, there's 0 net gain on build times. Ofc the dependency diagram is much more complex, but I hope the idea is conveyed.

In your experience as gradle consultant, from build times perspective, is it worth pursuing breakdown of modules into new `-domain` modules?

If it is worth exploring this path, I wonder if there's an existing tool to prevent breaking closed architecture principles.

We are a team of 9 devs, so I dream of a way to keep build times from slowly increasing over time.

**Comment by runningcode** [comment]
Hi @Maragues I appreciate your question and your interest in the Gradle Doctor.
This question has more to do with the Gradle build tool itself than with Gradle Doctor. I suggest you ask this question in the Gradle community slack: https://gradle.com/slack-invite or the Gradle forums https://discuss.gradle.org/
There are many Gradle experts from the community around the world and the Gradle team itself which will be willing to help you.

**Comment by Maragues** [comment]
Thanks @runningcode, you are right this isn't the right place for such requests

I created the following post on the forums https://discuss.gradle.org/t/should-we-break-expensive-modules-into-domain-modules/38710
