### ISSUE TITLE
Warn (fail?) when caching is not enabled

### ISSUE THREAD

**Issue by LouisCAD** [runningcode/gradle-doctor#189]
Hello, my name is Louis CAD, and after working on a project for more than 7 years, I just realized that the reason the `:buildSrc:compileKotlin` task kept being run lately is because Gradle caching wasn't enabled. To be more specific, I didn't have the following line in the `gradle.properties` file of that project (which I work on every day at work):

```properties
org.gradle.caching=true
```

FYI, the `:buildSrc:compileKotlin` takes between 20 and 45 seconds to run each time on my machine (MBP 13" 2020, Intel i5 10th Gen).

Of course, I wish the default was different from no caching, but until Gradle catches-up with this kind of UX issues, I think it'd be great to have Gradle Doctor fail the build by default when caching is not enabled, explaining the issues we are exposed to, and allowing to be ignored if needed, as is done for other checks that Gradle Doctor does.

If you agree, I can send a draft PR.

Thank you :)

All the best,

Louis CAD

**Comment by runningcode** [comment]
Thanks for reporting. Even if your build cache was disabled, your `buildSrc:compileKotlin` would not re-execute unless the inputs have changed or the build outputs were cleared by `clean` due to `up-to-date` checks.

I hesitate to include this as a default feature. I hate to make the Gradle Doctor more complicated or noisy for such a flag, that being said if it seems like a big community pain point, I would welcome improving this. I would like to hear more voices in favor of this feature before deciding to build it.

**Comment by LouisCAD** [comment]
> Even if your build cache was disabled, your buildSrc:compileKotlin would not re-execute unless the inputs have changed or the build outputs were cleared by clean due to up-to-date checks.

I wish that was true (and it's what I expected). In practice, for some reason, without caching enabled, Gradle keeps re-running the `:buildSrc:compileKotlin` task from scratch, and then, the subsequent tasks are deemed up-to-date, because, well, the compiler output is the same as before…

**Comment by runningcode** [comment]
Please check a build scan. It will tell you exactly why that task was re-executed.

**Comment by runningcode** [comment]
Closing in favor of #177
