### ISSUE TITLE
Check for clean task dependencies obsolete

### ISSUE THREAD

**Issue by ubuntudroid** [runningcode/gradle-doctor#201]
The check for clean task dependencies introduced [here](https://github.com/gradle/gradle/issues/2488) seems to be obsolete, now that this has been [fixed on gradle's end](https://github.com/gradle/gradle/issues/2488).

I guess it can simply be removed?

**Comment by runningcode** [comment]
That is correct, it has been fixed by Gradle.
In the [Gradle Doctor 0.8.0](https://runningcode.github.io/gradle-doctor/changelog/#080) this check is disabled by default when running Gradle 7.4 or higher.
For older Gradle versions the check is still enabled by default which is why it is not removed from the codebase.

**Comment by ubuntudroid** [comment]
Uh, nice, that's even better! 💯
